version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"  
      - "8000:8000"  # Prometheus metrics
    environment:
      - DATABASE_URL=sqlite:////app/mydatabase.db
      - SECRET_KEY=your_secret_key
    volumes:
      - .:/app
    networks:
      - observability

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - observability

volumes:
  grafana-storage:

networks:
  observability: